### PR TITLE
mlsdb: Update Mozilla Location DB offline data to 2022-03-22

### PR DESCRIPTION
**Pull request by abranson**
[mlsdb] Update Mozilla Location DB offline data to 2022-03-22. JB#57070

### CODE REVIEW

**Review by sledges — CHANGES_REQUESTED** [review]
Please match the commit subject format that's used in this repo, "[foo] bar. b#z".
I would also recommend changing bug#ref to 57070, so it's easier to keep track internally.

**Comment by abranson** [comment]
Done. Sorry, force of habit from other projects. We've been including that as the second line these days.

**Review by sledges — DISMISSED** [review]
It's a good practice to check commit history, so whenever we contrib, we match upstreams too:)
Bug#ref is still not the final one, my bad as I edited github comment which doesn't send emails.

**Comment by abranson** [comment]
Can anyone figure out why these new db files are dramatically smaller than the originals?

**Comment by sledges** [comment]
Looks like the whole DB's shrunk:
```
837.6M Feb 18  2021 MLS-full-cell-export-2021-02-18T000000.csv
365M   Mar 24 07:19 MLS-full-cell-export-2022-03-22T000000.csv
```
Seemingly less cell towers are now [known about?] in any given area that I tried, e.g.:
```
grep LTE,246,3 MLS-full-cell-export-2021-02-18T000000.csv | wc -l
3172
grep LTE,246,3 MLS-full-cell-export-2022-03-22T000000.csv | wc -l
1190
```
[MLS downloads](https://location.services.mozilla.com/downloads) say:
> The full cell export is limited to those cell networks whose position has been confirmed in the last 12 months.

Blame it on lockdowns = less movement of people? Following that should recover in the future. On the same page you can see tens of kB of compressed data already increasing daily.

**Comment by abranson** [comment]
We were missing the previously used export to compare. Thanks, looks like everything's working properly with a smaller source dataset then.

**Comment by sledges** [comment]
That might cause ~3 times less quick assisted fix if coverage is 3 times more sparse:)

**Comment by abranson** [comment]
Could also have been affected by the dropping of the Mozilla Stumbler data gathering app a year ago:

https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206

**Review by sledges — APPROVED** [review]

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
